### DISCUSSION TITLE
Blazor Server with OIDC Cookie Authentication behide IngressControler in Kubernetes

### DISCUSSION THREAD

**Discussion by alefcarlos** [dotnet/aspnetcore#56098] [Q&A]
Hey!

I'm in trouble trying to use Blazor Server with authentication. 

Running the application with authentication in the k8s cluster:

![image](https://github.com/dotnet/aspnetcore/assets/5452336/b8610628-43d1-4f87-98ea-4136a496c9d5)

And I proxied the request using Fiddler:

![image](https://github.com/dotnet/aspnetcore/assets/5452336/04575f36-49df-4a83-b16f-234653eae04e)

But a I have another app without authentication and It works as expected:

![image](https://github.com/dotnet/aspnetcore/assets/5452336/47b12a33-95e8-426e-a837-bcf0cb18f26b)

It the same case as this one in StackOverflow: https://stackoverflow.com/questions/74402608/net-6-c-sharp-blazor-server-websocket-connection-failed-after-openid-auth

But I have already configured the annotions

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    meta.helm.sh/release-name: abc-powerapps-ondemand-web
    meta.helm.sh/release-namespace: abc
    nginx.ingress.kubernetes.io/client-max-body-size: 100M
    nginx.ingress.kubernetes.io/large-client-header-buffers: 16 5M
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
    nginx.ingress.kubernetes.io/proxy-buffer-size: 5M
    nginx.ingress.kubernetes.io/proxy-buffers: 8 5M
```
I used big values to make sure it would be work rs

But it does not work :(

Does it has any other configuration do add ?

So, I tried it locally using nginx:

nginx.conf
```properties
http {
  server {
    listen 80;
    listen [::]:80;
    server_name localhost;
    proxy_buffers 8 128k;
    proxy_buffer_size 32k;
    large_client_header_buffers 16 128k;

    location / {
      proxy_pass http://app:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
```

docker-compose.yml:
```yaml
version: '3'
services:
  app:
    image: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_SERVICE_NAME=abc-powerapps-ondemand-web

  app2:
    image: web2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
```

And it work as expected. The same application
