### DISCUSSION TITLE
Blazor WASM Integrity issues with Azure Static Web Apps

### DISCUSSION THREAD

**Discussion by fingers10** [dotnet/aspnetcore#57045] [Q&A]
I recently published my `Blazor WASM` app to `Azure static web apps`. I'm using my custom build and publishing the output to Azure static web apps using the following action in yml.

```yml
- name: Publish Blazor Project
  run: dotnet publish ./Web/Web.csproj -c:Release --no-restore -o dist/Web --nologo

- uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: "upload"
    ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
    # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
    app_location: "dist/Web/wwwroot" # App source code path
    api_location: "" # Api
    output_location: "" # Built app content directory - optional
    skip_app_build: true # Skip build - optional
    ###### End of Repository/Build Configurations ######
```

I have the `staticwebapp.config.json` placed in the `wwwroot` of my blazor app.

Here is the content of `staticwebapp.config.json`:
```json
{
    "navigationFallback": {
      "rewrite": "index.html"      
    },
    "mimeTypes": {
      ".json": "text/json"
    }
  }
```

Now When I access the page, I get the following integrity error in browser console.

Here is the error screen print:

![image](https://github.com/user-attachments/assets/779e6924-6638-4ddb-9025-681644129266)

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/staticwebapp.config.json' with computed SHA-256 integrity 'Y4zkp0LpTVetcAY96ckDWdIeBi7tMyNFMD5PDHdo+sQ='. The resource has been blocked.
```

Please can you assist me on what I'm missing?
