### ISSUE TITLE
trying to publish blazor wasm app

### ISSUE THREAD

**Issue by gohopo** [dotnet/aspnetcore#18188]
### Describe the bug
I'm trying to publish blazor wasm app to GitHub Pages and aliyun oss using GitHub Actions.
Deploy success,but get error on browser([see console log](https://gohopo.github.io/)).
What I do wrong?

My web.yml
```
name: deploy to web
on:
  push:
    paths: 
    - 'src/Orion.UI.Web/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup dotnet core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

    - name: build
      run: dotnet publish ./src/Orion.UI.Web/Orion.UI.Web.csproj -c Release -o ./bin/publish
    
    - name: deploy to aliyun oss
      run: ossutil cp -rf ./bin/publish/Orion.UI.Web/dist oss://gohopo-orion/

    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAGES_TOKEN }}
        EXTERNAL_REPOSITORY: gohopo/gohopo.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./bin/publish/Orion.UI.Web/dist
```

action result:
![actions](https://user-images.githubusercontent.com/8192266/71986387-607c4a80-3267-11ea-94b4-bf98918cf349.jpg)

error on browser:
![404](https://user-images.githubusercontent.com/8192266/71986481-86095400-3267-11ea-8dbf-152ad25ba7dd.jpg)

### To Reproduce
My .csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.1.0-preview4.19579.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.1.0-preview4.19579.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.1.0-preview4.19579.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.1.0-preview4.19579.2" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

### Further technical details
- Microsoft.AspNetCore.Blazor 3.1.0-preview4.19579.2
- dotnet-version: 3.1.100
- github actions build
