### ISSUE TITLE
Upgrading .NET 5.0.100-preview.8 -> 5.0.100-rc.1 breaks Azure App Service VNet Cosmos service endpoint

### ISSUE THREAD

**Issue by pheuter** [dotnet/aspnetcore#26013]
Upon upgrading the .NET 5 SDK to the latest release candidate, my ASP.NET Core Web API application started throwing 403 forbidden access errors from Cosmos because it was failing to connect via the configured vnet subnet service endpoint:

```
One or more errors occurred. (Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: abe90d17-b2be-4faf-9a8e-c826638e6aaf; Reason: (Request originated from client IP xx.xxx.xx.xx through public internet. This is blocked by your Cosmos DB account firewall settings.
ActivityId: abe90d17-b2be-4faf-9a8e-c826638e6aaf, Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.14393 cosmos-netstandard-sdk/3.11.4);) Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: abe90d17-b2be-4faf-9a8e-c826638e6aaf; Reason: (Request originated from client IP xx.xxx.xx.xx through public internet. This is blocked by your Cosmos DB account firewall settings.
ActivityId: abe90d17-b2be-4faf-9a8e-c826638e6aaf, Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.14393 cosmos-netstandard-sdk/3.11.4);
```

For context, the app is deployed via a GitHub Actions workflow as a self-contained app with the runtime bundled (since App Service hasn't shipped the .NET 5 stack yet):

```yaml
 - name: Setup .NET 5 Preview SDK
   uses: actions/setup-dotnet@v1.6.0
   with:
     dotnet-version: 5.0.100-rc.1.20452.10

- name: Publish app
  run: |
     dotnet publish /property:PublishReadyToRun=true -c Release -r win-x86 -o ./output

- name: Deploy to Azure App Service
  uses: Azure/webapps-deploy@v2
  with:
    app-name: my-appservice-app
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: ./output
```

The app is able to connect to Cosmos via the vnet service endpoint perfectly when using `5.0.100-preview.8.20417.9`, but breaks when all I do is change the version to `5.0.100-rc.1.20452.10`.

Could it have something to do with the newer **IIS runtime support (ASP.NET Core Module v2)**: 15.0.20246.0?
