### ISSUE TITLE
Calc() inside of @supports broken with minify

### ISSUE THREAD

**Issue by DouglasRiddle** [dotnet/aspnetcore#27526]
### Describe the bug
When a CSS ```calc()``` is used within an ```@supports``` section it is broken by ```bundleconfig.json``` minify.

### To Reproduce
A mostly default MVVM app has been created at https://github.com/DouglasRiddle/MinifyExample with two divs. One with the broken CSS inside of ```@supports``` and one working as expected in the base CSS.

### Further technical details
- ASP.NET Core 3.1

```CSS
@supports (top: max(0%)) {
    .minify-break {
        /* Expect 16px, get 0 due to leading space being removed from "+" on minify */
        padding: max(16px, calc(var(--mdc-shape-small, 4px) + 4px));
    }
}

.minify-okay {
    padding: max(16px, calc(var(--mdc-shape-small, 4px) + 4px));
}
```
becomes (notice ```)+ ``` instead of expected ```) + ```)
```CSS
@supports (top:max(0%)){.minify-break{padding:max(16px,calc(var(--mdc-shape-small,4px)+ 4px));}}

.minify-okay{padding:max(16px,calc(var(--mdc-shape-small,4px) + 4px))}
```
