### ISSUE TITLE
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.FileSystemGlobbing"

### ISSUE THREAD

**Issue by fabich** [dotnet/aspnetcore#27675]
After restoring, building and deploying to Azure Web App we are getting a `500.30 - ANCM In-Process Start Failure` exception

If we repeat deployment multiple times it sometimes works.

### Exceptions
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.FileSystemGlobbing, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.FileSystemGlobbing, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.ChangeTokenInfo..ctor
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.ChangeTokenInfo..ctor(CancellationTokenSource tokenSource, CancellationChangeToken changeToken)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddFilePathChangeToken(String filePath)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddChangeToken(String pattern)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at <Project>.APP.Program.BuildWebHost(String[] args) in /home/runner/work/<Project>/<Project>/<Project>.APP/Program.cs:line 24
   at <Project>.APP.Program.Main(String[] args) in /home/runner/work/<Project>/<Project>/<Project>.APP/Program.cs:line 19
```

### Further technical details
```
D:\home\site\wwwroot>dotnet --version
3.1.302

D:\home\site\wwwroot>do
D:\home\site\wwwroot>c
D:\home\site\wwwroot>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
  2.1.518 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
  3.1.108 [D:\Program Files (x86)\dotnet\sdk]
  3.1.302 [D:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.11 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.11 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by fabich** [comment]
We identified this issue. Our build server is running version 3.1.403 and Azure is running an older version.

**Comment by fabich** [comment]
Could this be connected to the newest release of Microsoft.Extensions.FileSystemGlobbing v3.1.10?
https://www.nuget.org/packages/Microsoft.Extensions.FileSystemGlobbing

**Comment by Pilchie** [comment]
1. Can you share your .csproj file?  
2. Is the dotnet info output above from your machine, or from your Azure host?
3. How are you deploying to Azure?  Visual Studio, GitHub Actions, Azure DevOps, or through Git Push?

**Comment by fabich** [comment]
1: .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UserSecretsId>xxx</UserSecretsId>
    <ApplicationInsightsResourceId>xxx</ApplicationInsightsResourceId>
    <ApplicationInsightsAnnotationResourceId>xxx</ApplicationInsightsAnnotationResourceId>
    <Version>1.10.3</Version>
    <PackageId>xxx</PackageId>
    <Authors>xxx</Authors>
    <Product>xxx</Product>
    <Copyright>xxx</Copyright>
    <Description>xxx</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/xxx/xxx</RepositoryUrl>
    <PackageTags>xxx api</PackageTags>
    <NoWarn>1701;1702;1705;1591;SCS0016;1573;</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="4.0.2" />
    <PackageReference Include="GeoCoordinate.NetCore" Version="1.0.0.1" />
    <PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="4.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0" />
    <PackageReference Include="Autofac" Version="6.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.0" />
    <PackageReference Include="Ical.Net" Version="4.1.11" />
    <PackageReference Include="FluentValidation" Version="9.2.2" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.AzureAppServicesIntegration" Version="3.1.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="Joonasw.AspNetCore.SecurityHeaders" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="4.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="5.6.3" />
    <PackageReference Include="Unchase.Swashbuckle.AspNetCore.Extensions" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\<Project>.BLL.BI\<Project>.BLL.BI.csproj" />
    <ProjectReference Include="..\<Project>.BLL.IM\<Project>.BLL.IM.csproj" />
    <ProjectReference Include="..\<Project>.BLL.LP\<Project>.BLL.LP.csproj" />
    <ProjectReference Include="..\<Project>.BLL.PF\<Project>.BLL.PF.csproj" />
    <ProjectReference Include="..\<Project>.BLL.MA\<Project>.BLL.MA.csproj" />
    <ProjectReference Include="..\<Project>.BLL.MP\<Project>.BLL.MP.csproj" />
    <ProjectReference Include="..\<Project>.DAL\<Project>.DAL.csproj" />
    <ProjectReference Include="..\<Project>.Libs\<Project>.<Project>.API.Core\<Project>.<Project>.API.Core.csproj" />
    <ProjectReference Include="..\<Project>.Libs\<Project>.<Project>.API.Common\<Project>.<Project>.API.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Cert\Dev.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\Authorization\" />
    <Folder Include="Modules\" />
  </ItemGroup>
</Project>
```
2: dotnet info is from azure machine. please find below dotnet info from build task on github action
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/runner/.dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/home/runner/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/home/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/home/runner/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
3: we are using github action. please find below github action script
```
name: Build and deploy on request to test-staging slot

on: push

# TODO:
# Set global .net core version for all actions
env:
  AZURE_WEBAPP_NAME: <Project>-eu1-api-test # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '3.1.x'   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '!staging')"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Read version
        uses: dotnet/nbgv@master
        with:
          path: <Project>

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      # Run dotnet build and publish
      - name: dotnet restore, build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      # Deploy to Azure Web apps
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST_STAGING  }} # Define secret variable in repository settings as per action documentation
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
          
      #### Debug for issue on stating environemnt (stating slot)
      - name: Upload staging files
        uses: actions/upload-artifact@v2
        with:
          name: staging-release
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      - name: get dotnet info
        run: dotnet --info
```
