### ISSUE TITLE
blazor.razor.css isolation with possibility to programatically change styles

### ISSUE THREAD

**Issue by suchoss** [dotnet/aspnetcore#27806]
### Is your feature request related to a problem? Please describe.
I think that css isolation is a cool feature. What I am missing though is a possibility to change styles programatically the same way I change html code in razor components.

### Describe the solution you'd like
eg. I would like possibility to use something like this in my isolated `razor.css` files.
``` css
.board {
    display: grid;
    grid-template-columns: repeat(6,32px);
    grid-template-rows: repeat(20,32px);
    grid-column-gap: 0;
    border: 2px dashed var(--accent-color,red);
    background-color: @MyColor;  /*MyColor value is injected from code*/    
    background-repeat: no-repeat;
    background-size: contain;
}
```

Thanks
