### ISSUE TITLE
_framework no longer included in spa published output

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#28149]
### Describe the bug
In asp.net core 3.1, doing a `dotnet publish` of a host project, that references a blazor wasm project, would include the "_framework" folder as part of the published "static content" for that wasm project. 

For example, my wasm project has `<StaticWebAssetBasePath>.spa/foo</StaticWebAssetBasePath>` and after publishing when targeting .net core 3.1, its static content includes the _framework folder:

![image](https://user-images.githubusercontent.com/3176632/100258670-3c892c80-2f3f-11eb-99e2-61dad39132ac.png)

Notice that the `_framework` folder has been published to the static assets directory for the individual blazor wasm project (i.e under the StaticWebAssetBasePath) - it's not shared with any other blazor spa projects that I might add to the same solution - they would each also get their own _framework folders.

After upgrading to .net 5, our build pipeline is still building / publishing the solution the same way, but this folder is now missing.

![image](https://user-images.githubusercontent.com/3176632/100258861-71957f00-2f3f-11eb-99ae-cc9b64cb5a19.png)

Instead, it seems all the spa's now have the same `wwwroot/_framework` folder at host level, and all their assemblies and dependencies live there. This is problematic for multiple reasons:

- Different spa's can no longer use different versions of blazor framework because the framework is singular and shared for all the spa's. 
- Different spa's can't use different versions of the same dependency because the dependencies for all the spa's are now all copied to the same folder - so I assume last one wins (or perhaps highest version wins haven't checked)

However these limitations were not present in the publshing model for .net core 3.1 - where each spa had its _framework and assemblies / dependencies published under its own static content folder - it allowed multiple spa's to run "side by side" without having to share dependencies or interfere with eachother, and it allowed the host to just server up each spa as a self contained set of static files. This isolation between the apps was beneficial to my application and solution.

Is there a remedy to get the 3.1 publishing model back when publishing our host project referencing a couple of blazor wasm projects? Here is our current publish step (DevOps pipeline yaml):

```
- task: DotNetCoreCLI@2
    displayName: Publish
    env:
      SEMVER: $(SEMVER)
    inputs:
      command: publish
      publishWebProjects: false      
      projects: '**/Server.csproj'    
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
      zipAfterPublish: True
      versioningScheme: byEnvVar
      versionEnvVar: 'SEMVER'


```

### To Reproduce
As above, publish a .net core 3.1 blazor host referencing a blazor wasm project, then do the same with .net 5 based solution, and compare the output.

### Exceptions (if any)
This was a breaking change to the publishing model in .net 5 blazor. Isolating different wasm projects (which should just be a bunch of static files) is being broken by the new publishing model which is imposing constraints not present before.

### Further technical details
- ASP.NET Core version: 5
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version VS 2019 Pro
