### ISSUE TITLE
Blazor static files bundle/cache

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/aspnetcore#29050]
I've CSS style in my angular app as following:

```css
@font-face {
    src: url(font.eot)
}
```
and I've font.eot in wwwroot

When I publish angular app, it becomes something like

```css
@font-face {
    src: url(font.7c912e00bad2995b662c.eot)
}
```

and in wwwroot, file gets renamed to font.7c912e00bad2995b662c.eot

This allows me to cache assets and the browser won't send a request for that file twice (even conditional get)

How can I achieve the same with blazor?

P.S.

I know blazor has cache storage for dll and wasm files
I'm also aware of asp-append-version="true" which makes it work for js and CSS files
But what should I do for png/font/SVG files without using PWA?
