### ISSUE TITLE
asp.netcore cpu throttle in k8s cluster

### ISSUE THREAD

**Issue by AthiraKornath** [dotnet/aspnetcore#29150]
### Describe the bug
Aspnet core applications cpu throttle on AKS cluster.

### To Reproduce

I am running a fresh AKS cluster, with a .net core webapi workload, the default weather application created by the asp.net core 3.1 VS2019 and deployed to a 3 node DSv2 AKS cluster with no other workload on cluster.

I have set request as 5m and limit 100m; usage as per azure Insights or grafana is 1.92m . And throttling >50% when the pod start itself . I see 5m is too little resource but the cluster report shows the usage is less than 2m and my limit(100m) is way high compared to 2m.

I had to remove cpu limit to remove the throttling or give a cpu limit high as 1 -2 full core.  why is .net /kestral (not sure what is using all cpu), the usage metrics  show very less usage. 

NOTE: I am using latest AKS v1.19 and Kernel version5.4.0-1034-azure, So CFS bug fix must be included in this Ubuntu kernel version.

You can see the screenshot, actual usage is less than the request and limit. showing the throttling.

### Exceptions (if any)

Include the exception you get when facing this issue
![image](https://user-images.githubusercontent.com/68682674/104006044-faa10680-51cb-11eb-89c0-8ff6e169f526.png)

### Further technical details
- ASP.NET Core 3.1
-

**Comment by BrennanConroy** [comment]
Can you share your kubernetes manifest?

**Comment by AthiraKornath** [comment]
Please find attached,
[Dockerfile.zip](https://github.com/dotnet/aspnetcore/files/5881974/Dockerfile.zip)

**Comment by shirhatti** [comment]
> I had to remove cpu limit to remove the throttling or give a cpu limit high as 1 -2 full core. why is .net /kestral (not sure what is using all cpu), the usage metrics show very less usage.

@AthiraKornath I'm not I follow what you mean by throttling? Besides the scheduler adhering to your specified limits, there's no additional throttling in the .NET runtime.

What is the observed behavior? And did you expect?

I tried deploying a trivial application with the same limits you specified:
```yml
      containers:
      - name: server
        image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "5m"
          limits:
            cpu: "100m"
            memory: "200Mi"
```

I was successfully sustain a workload in this configuration
![image](https://user-images.githubusercontent.com/4734691/107322807-077a7980-6a5a-11eb-8456-6772b301259a.png)
