### ISSUE TITLE
IDX20803 Error when using self signed or dev-certs on Linux Docker containers

### ISSUE THREAD

**Issue by BradRaynaudCIC** [dotnet/aspnetcore#30942]
### Describe the bug
Error occurs when attempting to access any route that is protected by an authorization policy. 
`[Authorize(Authorization.Policies.ManageAllUsersPolicy)]`

```
 fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
       IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
       System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
          at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
          at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
          at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
          at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
          at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
          at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
```

The error only occurs when attempting to run the website using either self-signed or dotnet dev certs passed into the container on runtime. On the Windows host machine we are able to utilize dev certificates without any errors. Thus, I suspect that it is a problem with the certificate itself. 

Additionally, I am able to access the configuration at 'https://localhost/.well-known/openid-configuration' when I navigate to the URL. 

Here are the two methods I tried to generate a self signed certificate:
- https://infiniteloop.io/powershell-self-signed-certificate-via-self-signed-root-ca/
- https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide
However, both resulted in the same error. 

**DockerFile**
```
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
WORKDIR /src

COPY ["DAL/DAL.csproj", "DAL/"]
COPY ["QuickApp/QuickApp.csproj", "QuickApp/"]
RUN dotnet restore "QuickApp/QuickApp.csproj"
COPY . .
WORKDIR "/src/QuickApp"
RUN dotnet build "QuickApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "QuickApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app



COPY --from=publish /app/publish .
COPY ["QuickApp/Assets", "Assets"]
COPY ["QuickApp/ClientApp", "ClientApp"]
RUN cd ClientApp && npm install

ENTRYPOINT ["dotnet", "QuickApp.dll"]
```

**Docker-Compose**
```
version: '3.4'

services:
  quickapp:
    user: root
    image: quickapp
    build:
      context: .
      dockerfile: QuickApp/Dockerfile
    environment:
      - WEB_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=securepw
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/server.pfx
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ~/.aspnet/https:/https:ro
```

So, my question is, does this look to be a certificate issue? If so, do you have any recommended configurations for a self signed certificate that would resolve this issue? Otherwise, please let me know if you have any questions!

### To Reproduce

I am currently working to produce a minimal repo that is able to reproduce this issue. 

### Further technical details
- .NET 5

**Comment by blowdart** [comment]
There's not a problem with the certificate, there's not been any trust set up for it, because linux has no concept of the certificate store. Furthermore, if you're going cross container in docker, it becomes "fun" due to hostnames. 

Your OS may have `update-ca-certificates` and doing something like

```
# Dockerfile
FROM some-base-image:0.1
ADD your_certificate.crt /container/cert/path/your_certificate.crt
RUN chmod 644 /usr/local/share/ca-certificates/your_certificate.crt && update-ca-certificates
```

may update the OS.

**Comment by BradRaynaudCIC** [comment]
Apologies for the slow response, I had my focus taken up by a hardware failure. Following your guidance I modified my Dockerfile and docker-compose.yml to the following:

```

version: '3.4'

services:
  quickapp:
    user: root
    image: quickapp
    build:
      context: .
      dockerfile: QuickApp/Dockerfile
    environment:
      - WEB_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/localhost.key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.crt
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ./conf.d:/https:ro
      ```
      
      ```
      FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
WORKDIR /src

COPY ["DAL/DAL.csproj", "DAL/"]
COPY ["QuickApp/QuickApp.csproj", "QuickApp/"]
RUN dotnet restore "QuickApp/QuickApp.csproj"
COPY . .
WORKDIR "/src/QuickApp"
RUN dotnet build "QuickApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "QuickApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app



COPY --from=publish /app/publish .
COPY ["QuickApp/Assets", "Assets"]
COPY ["QuickApp/ClientApp", "ClientApp"]
RUN cd ClientApp && npm install

ADD conf.d/localhost.crt /usr/local/share/ca-certificates/localhost.crt
RUN chmod 644 /usr/local/share/ca-certificates/localhost.crt && update-ca-certificates

ENTRYPOINT ["dotnet", "QuickApp.dll"]
```

However, when I try to access the protected route im still getting the same error

 >Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
 >Exception occurred while processing message.
 >System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
>at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
>IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
>System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
>at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
>at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
>at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()

I'm pretty sure you are right that this is a certificate trust issue but trusting the certificate does not seem to resolve the issue. Thoughts?
