### ISSUE TITLE
Blazor allow css to target event listeners

### ISSUE THREAD

**Issue by royberris** [dotnet/aspnetcore#32465]
### Is your feature request related to a problem? Please describe.

This is not a problem but a feature.

So what I mean is something like scoped css but for event listeners. So we can target css to elements that have a set of event handlers.

### Describe the solution you'd like

Below example:

`Example.razor`

```razor
<p>Text bla bla <span @onclick="DoSomething">click me</span> more text bla bla <span>Do not click me</span></p>
```

`Example.css`

```css
p span[onclick] {
  color: red;
}

// or

p span[event='onclick'] {
  color: red;
}
```

------

Of course we could do this by adding classes to the `span` elements that actually have a click listener. But please do not take my example as something I want to achieve. It's simply an easy to understand scenario on what my goal is.
