### ISSUE TITLE
.NET 6 and AKS - how to keep web app from snoozing?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/aspnetcore#40592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm hosting a rest api using .NET 6, hosted on AKS using the official image (mcr.microsoft.com/dotnet/aspnet:6.0).

During the day, when the traffic is crazy, the response avg response time for operation X rarely goes above 200ms, with the 99th percentile under 1sec. But during the middle of night (like 4am) there are some HUGE increase in response without any correlation, after all CPU is 100% clear, memory is basically empty, no concurrence, no nothing.

Operation X does not touch any kind of cache (whether in memory, redis, memchache, etc)

I've seen this behavior in the past. As it is pretty well documented, IIS used to put apps to sleep. This shouldn't happen here after all, this is hosted on Kestrel/Linux.

To check if this is the case here or not I created a simple app the loops a request for operation X every 2 sec and guess what? the response time kept at its peak performance! it performed great, have a look:
<img width="1065" alt="d6x7d" src="https://user-images.githubusercontent.com/5585339/157242394-80eda61a-9e21-4625-a953-8e7c02f5d70d.png">
the blue line is avg response time and red line is response count. Look how on the previous days there's always a spike counter-balancing the request count...

This leads me into believing that there is some kind of "sleeping" going around... Other than keep a bot making phantom requests, what else can I do?

### Expected Behavior

No degradation

### Steps To Reproduce

1. Create any api (can be the default template)
2. Publish it on AKS using the default .NET 6 mcr image
3. Issue a request (cold start)
4. Wait for some time (unknown amount, but I guess 30min will do)
5. Issue another request (should not be a cold start)

### .NET Version

Latests .Net 6

**Comment by davidfowl** [comment]
.NET apps don’t go to sleep when running on Kubernetes. I have apps using .net 6 running for days and I don’t see this behavior…

**Comment by davidfowl** [comment]
I can't explain it either but applications do no go to sleep when running in aks, or at least, it has nothing to do with ASP.NET Core.  I think you're going to have to narrow it down by collecting metrics and maybe adding more logs *and* collecting traces/profiles that might reveal more clues as to what's going on. 

> how do you explain that a bot issuing a dummy request every n seconds prevented the issue?

I'll re-run my experiment right now an update with the results 30 mins from now when I make the second request.

A couple more questions:
- Are you using ingress? If yes? Which one and how is it configured?
- If you are using ingress, can you try to reproduce the problem on a vanilla new project without ingress?

**Comment by Leonardo-Ferreira** [comment]
Yes I'm using ingress, a standard NGINX:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-gestorcartao-ingress
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: card-prd-ecommerce.mycompany.com
    http:
      paths:
      - backend:
          serviceName: api-gestorcartao-service
          servicePort: 80
        path: /(.*)
```
Unfortunately, no I can't try to reproduce without ingress... my DevOps guy says that an ingress is mandatory, something to do with AKS using internal IPs for the pods...
