### ISSUE TITLE
css isolation, ::deep behaves incorrectly for .class::deep > element

### ISSUE THREAD

**Issue by PheelaV** [dotnet/aspnetcore#42432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With reference to [child component support](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#child-component-support)

```css
.listing::deep > div {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
```
 
generates

```css
.listing::deep > div[b-o1x0imiw0b] {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
```

which is the same as if the style was originally defined as
```css
.listing >  div {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
```

### Expected Behavior

Selector generated as:

`.listing[b-{STRING}] > div`

as per the example in the documentation:

> For example, `div::deep > a` is transformed to `div[b-{STRING}] > a` (for example, `div[b-3xxtam6d07] > a`).

### Steps To Reproduce

[repro repo](https://github.com/PheelaV/BlazorDeepSelectBug)

### .NET Version

6.0.301

### Anything else?

This produces what I wanted to achieve
```css
.listing > ::deep div {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
```
generates
```css
.listing[b-o1x0imiw0b] >  div {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
```

and the same does 
```css
.listing ::deep > div {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
```
Two options come to my mind:
1) This is a bug.
2) This is a tiny documentation mistake?
