### ISSUE TITLE
`app.UsePathBase(pathBase);` does NOT work but `context.Request.PathBase = new PathString(pathBase);` does?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#42553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I run ASP.Net Core 6.0 on k8s with MetalLB load balancer and ingress which rewrites the path as follows:
```
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress 
  namespace: default 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels: 
    app: ingress 
spec:
  ingressClassName: public
  rules:  
  - host: 
    http:   
      paths:  
      - pathType: Prefix
        path: /aspnetcorewebapi(/|$)(.*)
        backend:
          service:
            name: svc-aspnetcorewebapi
            port:
              number: 443
```
The application gets an environment variable `PATH_BASE`. In `Program.cs`, 
```
    string pathBase = Environment.GetEnvironmentVariable("PATH_BASE");
    //app.UsePathBase(pathBase); No, doesn't work!
    app.UseRouting();
    app.Use(async (context, next) =>
    {
          context.Request.PathBase = new PathString(pathBase); // Kubernetes ingress rule. This works.
          await next(context);
    }
```
What's the difference between these 2? Which is the right one to use?

### .NET Version

6.0.301
