### ISSUE TITLE
Add support for display:content in Virtualize component

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#44619]
There is a [reported bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1321553) in chromium, that prevents from using `display:contents` in `ItemTemplate`.

```css
.grid {
    display: grid;
    grid-template-columns: 1fr;
}
.grid-row {
    display: contents;
}
```

```razor
<div class="grid" style="height: 800px; overflow: auto">
    <Virtualize TItem="Item" ItemsProvider="GetItemsAsync">
        <div class="grid-row" @key="context">
            <div class="grid-cell">
                @context
            </div>
        </div>
    </Virtualize>
</div>
```
as I have reported here: #38439

### Describe the solution you'd like

Would you mind to prioritize the fix by adding a comment to the bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=1321553 ?

It would open whole bunch of possibilities for virtualize component.

### Additional context

It has been fixed in FireFox as per my bug report
