### ISSUE TITLE
Blazor WASM project fails to publish when updating WebCompiler nuget package

### ISSUE THREAD

**Issue by cjoy-ant** [dotnet/aspnetcore#47201]
### This is my workflow:

```
name: Deploy Bazor WASM to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Portfolio/Portfolio.csproj -c:Release -p:GHPages=true -o dist/Portfolio --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GHPAGES_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/Portfolio/wwwroot
```

### This is the error that I'm getting at step 'Publish .NET Core Project'
```
Run dotnet publish Portfolio/Portfolio.csproj -c:Release -p:GHPages=true -o dist/Portfolio --nologo
  Determining projects to restore...
  Restored /home/runner/work/Portfolio/Portfolio/Portfolio/Portfolio.csproj (in 3.15 sec).
  
  WebCompiler: Begin compiling compilerconfig.json
  WebCompiler installing updated versions of the compilers...
/home/runner/.nuget/packages/buildwebcompiler/1.12.405/build/BuildWebCompiler.targets(12,[9](https://github.com/cjoy-ant/Portfolio/actions/runs/4418499367/jobs/7745705186#step:5:10)): error : An error occurred trying to start process 'cmd.exe' with working directory '/tmp/WebCompiler1.[12](https://github.com/cjoy-ant/Portfolio/actions/runs/4418499367/jobs/7745705186#step:5:13).405'. No such file or directory [/home/runner/work/Portfolio/Portfolio/Portfolio/Portfolio.csproj]
Error: Process completed with exit code 1.
```

I'm unsure if this specifically a WebCompiler issue or if I've made a mistake elsewhere...
