### ISSUE TITLE
Container publish not functioning in DN8.P2; Worked in DN7

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#47259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am attempting to publish to a container using a workflow running in github actions. This publish worked in DN7, but fails in DN8.P2 with an error logged of 'The "CreateNewImage" task failed unexpectedly.'

### Expected Behavior

I expect the publish to complete successfully

### Steps To Reproduce

The steps in the workflow that are pertinent are:
```
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Publish, tag, and push DS image
      run: |
        dotnet publish ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj --os linux --arch x64 --configuration Azure -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerImageName=${{env.appNameDS}}
        docker tag ${{env.appNameDS}}:${{ env.suffix }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.suffix }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.suffix }}
```

The failure occurs in the 'dotnet publish'  step

The logs show
```
  ICEBG.Client -> /home/runner/work/ICEBG/ICEBG/ICEBG.Client/bin/Azure/net8.0/ICEBG.Client.dll
  ICEBG.Web.DataServices -> /home/runner/work/ICEBG/ICEBG/ICEBG.Web.DataServices/bin/Azure/net8.0/linux-x64/ICEBG.Web.DataServices.dll
  ICEBG.Web.DataServices -> /home/runner/work/ICEBG/ICEBG/ICEBG.Web.DataServices/bin/Azure/net8.0/linux-x64/publish/
/home/runner/.nuget/packages/microsoft.net.build.containers/0.3.2/build/Microsoft.NET.Build.Containers.targets(114,9): error MSB4018: The "CreateNewImage" task failed unexpectedly. [/home/runner/work/ICEBG/ICEBG/ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj]
/home/runner/.nuget/packages/microsoft.net.build.containers/0.3.2/build/Microsoft.NET.Build.Containers.targets(114,9): error MSB4018: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).) [/home/runner/work/ICEBG/ICEBG/ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj]
```
The repository is open source and available at [https://github.com/MarkStega/ICEBG](https://github.com/MarkStega/ICEBG)

The full log of the failed run is available at [https://github.com/MarkStega/ICEBG/actions/runs/4439861459/jobs/7792909114](https://github.com/MarkStega/ICEBG/actions/runs/4439861459/jobs/7792909114)

### .NET Version

DN8.P2
