### ISSUE TITLE
QuickGrid in NET 8 - column resizing

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#47494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use QuickGrid and the only feature that is missing is column resizing. As a simple component, it is almost feature complete and column resizing is the only missing part.

### Describe the solution you'd like

It should be possible to resize the column with a mouse or touch. It should be possible to set column width in code.

**Comment by aburakab** [comment]
For now, I used resize css :) for my header. Also you can customize the header like this `<HeaderTemplate>`
Maybe the double click auto-fit is the thing that we need :)
```css
.col-title {
    scroll-padding: 0;
    resize: horizontal;
    overflow: hidden;
    min-width: 120px;
    max-width: 350px;
}
```
