### ISSUE TITLE
How to publish .net 8 preview 7 blazor wasm AOT to github pages

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/aspnetcore#50215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a .net 8 preview 7 blazor wasm project that published to github pages in this link :
https://mammadkoma.github.io/MySite/
I can publish after push to github, I just want to publish in AOT mode for better startup time.
But when I add **PublishAot true** in csproj file and publish to github , the github shows error in Actions tab:

**Run dotnet publish MySite/MySite.csproj -c Release -o release --nologo
  Determining projects to restore...
Error: /home/runner/.dotnet/sdk/8.0.100-preview.7.2337[6](https://github.com/mammadkoma/MySite/actions/runs/5918664829/job/16048203193#step:4:7).3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'browser-wasm'. [/home/runner/work/MySite/MySite/MySite/MySite.csproj]
Error: Process completed with exit code 1.**

The main.yml :
```
name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.x
                  include-prerelease: true

            - name: Publish .NET Core Project
              run: dotnet publish MySite/MySite.csproj -c Release -o release --nologo

            - name: copy index.html to 404.html
              run: cp release/wwwroot/index.html release/wwwroot/404.html

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: release/wwwroot
```

.csproj file :
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<RunAOTCompilation>true</RunAOTCompilation>-->
		<PublishAot>true</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-preview.7.23375.9" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-preview.7.23375.9" PrivateAssets="all" />
		<PackageReference Include="MudBlazor" Version="6.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>
</Project>
```

### Expected Behavior

Publish blazor wasm in aot mode

### .NET Version

8.0.0-preview.7.23375.9
