### ISSUE TITLE
GitHub Action block on dotnet test with multiple WebApplicationFactory

### ISSUE THREAD

**Issue by vernou** [dotnet/aspnetcore#51551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

GitHub Action block step `dotnet test` with multiple static (but disposed) `WebApplicationFactory`.

### Expected Behavior

GitHub Action execute the tests and finish.

### Steps To Reproduce

1. Create a GitHub repository
2. Clone the repository
3. Initialize projects like
```bash
dotnet new webapi --name AwesomeApi --framework "net7.0"
dotnet new xunit --name AwesomeApi.Tests --framework "net7.0"
dotnet add AwesomeApi.Tests reference AwesomeApi
dotnet add AwesomeApi.Tests package Microsoft.AspNetCore.Mvc.Testing
ECHO public partial class Program { } >> ".\AwesomeApi\Program.cs"
```
4. Replace the file `AwesomeApi.Tests\UnitTest1.cs` by :
```csharp
using Microsoft.AspNetCore.Mvc.Testing;

namespace AwesomeApi.Tests;

public class UnitTest1 
{
    static UnitTest1()
    {
        using var factory = new WebApplicationFactory<Program>();
        using var client = factory.CreateClient();
        using var httpResponse = client.GetAsync("ok").Result;
    } 

    [Fact]
    public void Test()
    { }
} 

public class UnitTest2
{
    static UnitTest2()
    {
        using var factory = new WebApplicationFactory<Program>();
        using var client = factory.CreateClient();
        using var httpResponse = client.GetAsync("ok").Result;
    }
    
    [Fact]
    public void Test()
    { }
}
```
5. Add the file `.github\workflows\test`
```yaml
name: test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dotnet test
      run: dotnet test AwesomeApi.Tests
```
6. Commit all and push

### .NET Version

7.0.402

### Anything else?

Example :
https://github.com/vernou/azertyuio/actions/runs/6605709517/job/17941162441

Workaround :
Split `WebApplicationFactory` in test project.
