### ISSUE TITLE
CSS nesting does not work fully in isolated CSS files

### ISSUE THREAD

**Issue by alasdair-cooper** [dotnet/aspnetcore#52422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using CSS nesting in an isolated CSS file, some scenarios do not work at all and others do not behave as expected.

### Expected Behavior

If the intention is to work as the existing system does, then only the "leaf" nodes of the nested CSS should be given the attribute selector, the parent should never have it. Furthermore if a `::deep` is used, then isolated CSS attributes should not be applied to *any* of a parents children. 

### Steps To Reproduce

With a set of classes as the following:

```css
.parent {
    & .child-1 {

    }

    & .child-2 {
        
    }
    
    & .child-3 {
        
    }
}
```
This output will be produced in the `*.styles.css`:
```css
.parent[b-7apb7xee7k] {
    & .child-1 {

    }

    & .child-2[b-7apb7xee7k] {
        
    }
    
    & .child-3[b-7apb7xee7k] {
        
    }
}
```
All rules have the attribute selector except the first child. 
When you use `::deep` like so:
```css
::deep .parent {
    & ::deep .child-1 {

    }

    & ::deep .child-2 {
        
    }
    
    & ::deep .child-3 {
        
    }
}
```
You get an output thus:
```css
[b-7apb7xee7k] .parent {
    & ::deep .child-1 {

    }

    &[b-7apb7xee7k]  .child-2 {
        
    }
    
    &[b-7apb7xee7k]  .child-3 {
        
    }
}
```

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@alasdair-cooper thanks for contacting us.

We currently don't support nesting in scoped CSS.

**Comment by Rowe2ryWA** [comment]
This would be greatly helpful. Really, I want the generated css to see the `::deep` selector and then just NOT put scoping tags on anything after that.

Code:
```
::deep .group-accordion-header {
    .oc-grid-layout {
        background-color: var(--clr-1p50);

    .dark & {
        background-color: var(--clrd-1p400);
    }
    
    &:has(section[aria-expanded="True"]) {
        .oc-grid-layout {
            background-color: var(--clr-1p75);
            
            .dark & {
                background-color: var(--clrd-1p500);
            }
        }
    }
```

But is adding extra scoping attributes I don't want.
![image](https://github.com/user-attachments/assets/b4c17e88-fcf7-4513-a8f5-17f625a3b126)

**Comment by ChinaChenMingQuan** [comment]
I'd love to have this feature too, it would cut down on a lot of code! This suggestion hasn't been supported since 2023 and now it's almost 2025!

--- deepl translator

**Comment by gulbanana** [comment]
This is becoming more of a problem over time as CSS nesting is increasingly used.

**Comment by rezapps** [comment]
I noticed the same issue on windows (win11), when moved a blazor project from wsl. dotnet in wsl (fedora) processes nested CSS correctly. dotnet version installed on windows and in wsl is dotnet-sdk-9.0.101

**Comment by zotanmew** [comment]
When using nesting in scoped css files, sometimes outright invalid css is generated, e.g.

```css
.root {
    .child {
        font-size: 12pt;
    }
    
    .child2 {
        font-size: 13pt;
    }
    
    color: red;
    background-color: green;
}
```

gets turned into

```css
.root[b-ch0kpto8ry] {
    .child {
        font-size: 12pt;
    }
    
    .child2[b-ch0kpto8ry] {
        font-size: 13pt;
    }
    
    color: red;
    background-color: green;[b-ch0kpto8ry]
}
```

(notice the trailing attribute selector)

**Comment by Rowe2ryWA** [comment]
@danroth27 this was the open issue mentioned in the table talk at Build.

I run into this problem multiple times per day daily.

Currently this issue is resulting in me having to do workarounds like this.

![Image](https://github.com/user-attachments/assets/6858b84a-1574-4f0d-8dbc-53a4c2427273)

because this one
![Image](https://github.com/user-attachments/assets/f47af4f0-9c6f-465f-a235-ab1fd2757842)

was compiling to this in the browser
![Image](https://github.com/user-attachments/assets/00a8e78a-ce24-4839-9463-a373105e6b34)

You can see it sort of.. half works and half doesn't which is also giving a false sense of security that Blazor IS handling this nesting because it usually will work correctly for a first nested child, but then fall apart for subsequent ones etc. See how it only added the 2nd attribute tag on one of the children and not both?

Is there anything you can do to raise awareness to the this pain point for the asp net core team?

**Comment by CDTR-MattConroy** [comment]
This would greatly simplify the CSS we could write if supported. The current implementation generates confusion more than anything, due to it appearing to work for the first nested element, but no others, Is there a process to bump this up the chain other than adding a +1 to here?

**Comment by Funkest** [comment]
At present, CSS nesting must be considered effectively non-functional within Blazor CSS isolation. This is despite CSS nesting being extremely effective for code organization. I (We) strongly hope for improvements.

**Comment by Rowe2ryWA** [comment]
> At present, CSS nesting must be considered effectively non-functional within Blazor CSS isolation. This is despite CSS nesting being extremely effective for code organization. I (We) strongly hope for improvements.

In addition to readability and code organization/maintainability, It also reduces bundle size and makes css files smaller.

Before using something like an scss pre-processor on
```css
.some-class {
    padding: 2rem;

    &.other-class {
        margin-inline: auto;

        button {
            background-color: red;
        }
        p {
            color: blue;
        }
    }
}
```

would expand to
```css
.some-class {
    padding: 2rem;
}
.some-class.other-class {
    margin-inline: auto;
}
.some-class.other-class button{
    background-color: red;
}
.some-class.other-class p {
    color: blue;
}
```

writing out the full selector chain each time. Its the nested css looks like more code in a way because its 14 lines vs 12 lines for the scss output, but if you minify both, the character count is 104 characters for nested and 161 for what a preprocessor would do to it (thats 50% more on just this one small example with just 2 levels of nesting, real world examples with more layers of nesting would grow exponentially with each "layer"). Not to mention Blazor working with preprocessors is ALSO not supported, But you would still have to manually type out the expanded stuff that was 50 characters more without the preprocessor if you couldn't rely on the nesting.
