### ISSUE TITLE
Latest .NET SDK 8.0.20 update causes build failures in Azure devOps hosted pools with latest Visual Studio

### ISSUE THREAD

**Issue by dipakboyed** [dotnet/aspnetcore#54023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Description of Issue: Our 1ES based Hosted Agent build pipeline is configured to use latest .NET 8.0.x SDK and latest Visual Studio version. Starting today with the release of .NET SDK 8.0.20, our builds have pulled in the latest .net SDK but it appears the hosted machines also need a compiler/VS upgrade. We see build failures like 

 Error CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. 
 
Please advise how Azure DevOps pipelines with settings to use latest Visual Studio versions can be fixed. This is a complete work stopper for our team

### Expected Behavior

ADO hosted agents with latest Visual Studio should be able to compile .Net 8.0.20 SDK based projects

### .NET Version

8.0.20

**Comment by EvaRichie** [comment]
Greetings I found a way to work around how to prevent this issue, by add the usedotnet task into pipeline. here I use the YAML.

``` YAML
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: sdk
    version: '8.0.102'
```

Then just use the normal way with VSBuild task with YAML

``` YAML
- task: VSBuild@1
  displayName: 'Build main solution'
  inputs:
    solution: '$(BuildSolution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
```
