### ISSUE TITLE
Unable to rename ICUDT.dat file in Blazor WASM App Hosted(client server) project publish

### ISSUE THREAD

**Issue by praveenpallekaate** [dotnet/aspnetcore#54943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have Blazor WASM App Hosted application. It has Client & Server project. It was in .Net 7, then i migrated to .Net 8 & client project with `WasmEnableWebcil` option as the .dll's wer blocked. After the migration .dat files got blocked & followed [this](https://github.com/dotnet/runtime/issues/89073) post.

`Client.csproj`
```
...
  <!-- After the application is build/published -->
  <Target Name="RenameIcuToAppBundle" AfterTargets="Build">
    <Message Text="Rename ICU called!"/>
    <Message Text="$(OutputPath)"/>
    <ItemGroup>
      <!-- Find all ICU files in AppBundle -->
      <IcuFiles Include="$(OutputPath)\**\*.dat" />
    </ItemGroup>

    <!-- Change their extension to 'NewIcuFileExtension' -->
    <Move SourceFiles="@(IcuFiles)"
      OverwriteReadOnlyFiles="true"
      DestinationFiles="%(RelativeDir)%(Filename)$(NewIcuFileExtension)" />
  </Target>
...
```
First Approach:
I added the above to client csproj file and icudt.dat is getting renamed on local build & on DevOps publish, but the server csproj publish stage it fails with `icudt.dat` file missing message as below.
`WebAssembly.Browser.targets(561,5): error MSB3954: Failed to compute hash for file 'D:\a\1\s\src\Client\bin\Release\net8.0\wwwroot\_framework\icudt.dat' because it does not exist or is inaccessible.`

Second Approach:
When i add the same setting to server csproj the rename does not work for `AfterTargets` on `Build`, `Publish` or both. The publish artifact zip show icudt.dat file in wwwroot\\_framework folder as is. Below is the DevOps yaml to publish.

```
...
      # Build.
      - task: DotNetCoreCLI@2
        displayName: '🔨 dotnet build'
        inputs:
          command: 'build'
          projects: |
            src/Server.csproj
          arguments: '--no-restore --configuration Release'

      # Optimise and publish web package.
      - task: DotNetCoreCLI@2
        displayName: '📦 dotnet publish'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: |
            src/Server.csproj
          arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)'

      # Publish artifacts.
      - task: PublishBuildArtifacts@1
        displayName: '📤 Publish artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Server.zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'
```
How do i go ahead here, should id modify `blazor.boot.json` & is it possible?

### .NET Version

8.0.203
