### ISSUE TITLE
MVC View not found when deploying to Azure with Azure DevOps pipeline since SDK 8.0.200

### ISSUE THREAD

**Issue by Eirenarch** [dotnet/aspnetcore#56298]
Not sure where to report this but since the release of .NET SDK 8.0.2 my builds in Azure DevOps that deploy to Azure do not include the MVC razor views so the websites can't find them. If I modify the pipeline to fix the SDK to 8.0.100 they work as intended. I downloaded and decompiled the dll deployed with the 8.x setting and indeed it does not contain AspNetCoreGeneratedDocument namespace with the compiled views. I verified that with 8.x setting Azure DevOps pipeline logs do indeed show 8.0.200 as the version of the SDK used. If I publish a build to locally to a folder on my computer the dll does contain the MVC views

### To Reproduce
Not sure honestly.
This is the relevant part of the pipeline yaml

```
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1
  displayName: Use NuGet

- task: NuGetCommand@2
  displayName: NuGet Restore
  inputs:
    restoreSolution: '$(solution)'
    command: restore

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```
