### ISSUE TITLE
Document that QuickGrid may render additional empty rows on the last page when using a paginator that should be appropriately styled

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#59096]
When you use a paginator with QuickGrid, it may render additional empty rows on the last page to fill it out and make it easier to style the grid to be a fixed height. We should document this behavior and recommend accounting for these extra empty rows in the app's styling.

Related discussion: https://github.com/dotnet/aspnetcore/issues/57199

**Comment by guardrex** [comment]
> Perhaps we changed the CSS and regressed this.

QuickGrid of 8.0 didn't produce `<td>` elements in rows unpopulated with data (and ***zero*** or more `<td>`s are permitted by the spec). In 9.0, empty `<td>` elements are being produced in those rows, so Bootstrap is adding a `border-bottom-width` via ...

```css
.table > :not(caption) > * > * {
    ...
    border-bottom-width: var(--bs-border-width);
    ...
}
```

Playing off of the Bootstrap style (added to `app.css`) ...

```css
.table > :not(caption) > tr > td:empty {
    border-bottom-width: 0;
}
```

... works if all of the cells of populated rows have a value, but that's not a good general assumption.

Otherwise, there are no distinguishing classes on these empty rows/cells to solve this easily. JS could take care of it, but that's not great.

**Comment by danroth27** [comment]
@guardrex The intent behind adding the empty rows and cells is to facilitate styling the QuickGrid so that it has a stable height and styling across all pages of data. So, what we want to document here is not hiding the styling of the empty cells but styling all the rows to have a consistent height when using pagination. Something like:

```css
::deep td {
    height: 2em;
}
```

**Comment by danroth27** [comment]
Opened https://github.com/dotnet/AspNetCore.Docs/issues/34211 to track the doc updates.

**Comment by guardrex** [comment]
I'll move the discussion over to the issue. I need more information.

**Comment by asymetrixs** [comment]
There seems to be an attribute 'aria-rowindex' on rows that have content. It is missing on empty rows.
So it is possible to hide those rows using css:

```css
tbody tr:not([aria-rowindex]) 
{
    display: none;
}
```
